### ISSUE TITLE
failing to get cert?

### ISSUE THREAD

**Issue by malikshi** [M3chD09/shadowsocks-with-v2ray-plugin-install#1]
I'm trying it for 3 times and same problem.

**Comment by M3chD09** [comment]
> I'm trying it for 3 times and same problem.

Make sure you have pointed your domain to the IP address of your server with A record.
Or you may have hit a [rate limit of Let’s Encrypt](https://letsencrypt.org/docs/rate-limits/)?
You can provide more information here, such as the server's operating system and the information before `Failed to get cert` in the terminal when running this script.

**Comment by BigeYoung** [comment]
You'd better 留一个 choice that 没有域名 then disable https.
Anyway, it's 有趣的 that two 中国人 talked in English.
