### ISSUE TITLE
Shadowsocks windows 插件不好使

### ISSUE THREAD

**Issue by C500mg** [M3chD09/shadowsocks-with-v2ray-plugin-install#3]
你好，我按照您博客中的步骤安装了插件，启动没有问题，当使用Shadowsocks windows 填写插件程序时，就不好使了，不知道问题出在哪里，我的ss是使用下面命令安装的，应该不是这个问题吧
yum install m2crypto python-setuptools
easy_install pip
pip install shadowsocks

启动命令为
ssserver -c /etc/shadowsocks.json -d start
以下是配置文件，域名我临时随便改了
{
    "server": "0.0.0.0",
    "server_port": 443,
    "local_port": 1080,
    "password": "123123",
    "timeout": 300,
    "method": "aes-256-cfb",
    "plugin": "v2ray-plugin",
    "plugin_opts": "server;tls;cert=/etc/letsencrypt/live/www.aa.cn/fullchain.pem;key=/etc/letsencrypt/live/www.aa.cn/privkey.pem;host=www.aa.cn;loglevel=none"
}

**Comment by M3chD09** [comment]
你好，
Shadowsocks的Windows客户端具体提示什么错误呢？
服务器端推荐使用[shadowsocks-libev](https://github.com/shadowsocks/shadowsocks-libev)，此版可以和v2ray-plugin插件配合使用，python版可能不兼容。
请确认客户端解压出的v2ray-plugin插件是exe格式，如果你使用7-zip解压tar.gz文件的话需要解压两次。
