### ISSUE TITLE
关于配置手机

### ISSUE THREAD

**Issue by tztnuaji** [M3chD09/shadowsocks-with-v2ray-plugin-install#5]
请问默认的插件信息该怎么写，就是那个transport mode和path，不清楚怎么重新调出刚安装完后显示的配置信息。

**Comment by tztnuaji** [comment]
transport mode：websocket-tls
hostname：xxxxx
path：/
concurrent connections：1
cert：自己下载privkey.pem

请问这样是否正确呢？

**Comment by M3chD09** [comment]
> transport mode：websocket-tls
> hostname：xxxxx
> path：/
> concurrent connections：1
> cert：自己下载privkey.pem
> 
> 请问这样是否正确呢？


你好，  
如果使用本脚本一键安装服务端的话，这样是正确的  
另外，使用可信任的SSL证书配置服务端的话，无需填写cert（本脚本安装的也无需填写）  
其它情况则需要填写cert
