### ISSUE TITLE
86行代码需要更新

### ISSUE THREAD

**Issue by korykim** [M3chD09/shadowsocks-with-v2ray-plugin-install#7]
> 需要添加 `--no-check-certificate`
```
wget https://tls.mbed.org/download/mbedtls-$MBEDTLS_VER-gpl.tgz --no-check-certificate
```

**Comment by M3chD09** [comment]
你好，
感谢你的建议，在前段时间该网站的SSL证书配置有问题时候确实有用。
但是`-no-check-certificate`可能会带来一些安全性问题，比如容易遭到**MITM**（中间人攻击），所以不推荐添加。现在该网站SSL证书配置问题已经修复，脚本可以正常使用了。
